### PR TITLE
Find email by title then check the recipents

### PR DESCRIPTION
**Pull request by jeffreyguo**
Find an email by three fields in one step: from address, to address and title

### CODE REVIEW

**Comment by chillu** [comment]
Hmm, I'm not a big fan of the increased complexity from this - we already have `/^there should (not |)be an email (to|from) "([^"]*)" titled "([^"]*)"$/` and `/^there should (not |)be an email (to|from) "([^"]*)"$/` - which you could combine to achieve some of this. Not as accurate as a single step though. Ideally we could "back reference" the matched email in further steps:

```
Given there is an email titled "Feedback"
And the email is sent from sender@test.com
And the email is sent to recipient@test.com
```

You already have `EmailContext->$lastMatchedEmail` to use for this. Wanna give it a shot?

**Comment by jeffreyguo** [comment]
Ok now, change it to simple steps, see commit[64c4819].

**Comment by chillu** [comment]
That's awesome, thanks Jeffrey - and sorry for the late merge :( Oh, just a minor thing for more pull requests: Please always include an example of the step in the PHPDoc, since it makes it easier to track down

**Comment by jeffreyguo** [comment]
Thanks @chillu , I will add examples next time.

**Pull request merged**
