### PR TITLE
Bump to use PHPUnit 4.8 / stable packages

### PR DESCRIPTION
**Pull request by dhensby**

### CODE REVIEW

**Comment by chillu** [comment]
This will break all SilverStripe modules running Behat at the moment, since they call `require_once 'PHPUnit/Autoload.php';` as part of their `FeatureContext.php` definitions. Probably no longer necessary given that PHPUnit should be autoloaded through composer, but that line will still cause a fatal error. I can think of at least the `cms` and `siteconfig` modules requiring fixes here.

**Comment by chillu** [comment]
@dhensby As stated above, the require calls still break the module. Can you try applying the following patch to tis PR (via `git am`)? 

```
From 6b8f689cabaf2da0b5aa45099080ae27d4d6ad5f Mon Sep 17 00:00:00 2001
From: Ingo Schommer <ingo@silverstripe.com>
Date: Tue, 23 Feb 2016 22:51:56 +1300
Subject: [PATCH] Remove Behat-related code dependant on PHPUnit 3.x

We've upgraded SilverStripe core to PHPUnit 4.x now, and the Functions.php has moved locations.
Since all custom contexts either use one of these contexts, or extend off SilverStripeContext,
we can be certain that the required assertions are automatically included for custom contexts,
no need to duplicate the require_once() calls.

Note that Behat 3.x suggests using static methods on a class, e.g. PHPUnit_Framework_Assert::assertSame (see http://docs.behat.org/en/master/quick_intro.html).
This seems quite verbose, and increases the upgrade burden on any project using Behat.
---
 src/SilverStripe/BehatExtension/Console/Processor/InitProcessor.php | 4 ----
 src/SilverStripe/BehatExtension/Context/BasicContext.php            | 3 +--
 src/SilverStripe/BehatExtension/Context/EmailContext.php            | 3 +--
 src/SilverStripe/BehatExtension/Context/FixtureContext.php          | 3 +--
 src/SilverStripe/BehatExtension/Context/LoginContext.php            | 3 +--
 src/SilverStripe/BehatExtension/Context/SilverStripeContext.php     | 2 ++
 6 files changed, 6 insertions(+), 12 deletions(-)

diff --git a/src/SilverStripe/BehatExtension/Console/Processor/InitProcessor.php b/src/SilverStripe/BehatExtension/Console/Processor/InitProcessor.php
index b42c052..c273a14 100644
--- a/src/SilverStripe/BehatExtension/Console/Processor/InitProcessor.php
+++ b/src/SilverStripe/BehatExtension/Console/Processor/InitProcessor.php
@@ -153,10 +153,6 @@ use SilverStripe\BehatExtension\Context\SilverStripeContext,
     SilverStripe\Framework\Test\Behaviour\CmsUiContext,
     SilverStripe\Cms\Test\Behaviour;
 
-// PHPUnit
-require_once 'PHPUnit/Autoload.php';
-require_once 'PHPUnit/Framework/Assert/Functions.php';
-
 /**
  * Features context
  *
diff --git a/src/SilverStripe/BehatExtension/Context/BasicContext.php b/src/SilverStripe/BehatExtension/Context/BasicContext.php
index 2e06e90..a6a3e66 100644
--- a/src/SilverStripe/BehatExtension/Context/BasicContext.php
+++ b/src/SilverStripe/BehatExtension/Context/BasicContext.php
@@ -13,8 +13,7 @@ use Behat\Gherkin\Node\PyStringNode,
     Behat\Gherkin\Node\TableNode;
 
 // PHPUnit
-require_once 'PHPUnit/Autoload.php';
-require_once 'PHPUnit/Framework/Assert/Functions.php';
+require_once BASE_PATH . '/vendor/phpunit/phpunit/src/Framework/Assert/Functions.php';
 
 /**
  * BasicContext
diff --git a/src/SilverStripe/BehatExtension/Context/EmailContext.php b/src/SilverStripe/BehatExtension/Context/EmailContext.php
index 2ed15bd..a23f6ae 100644
--- a/src/SilverStripe/BehatExtension/Context/EmailContext.php
+++ b/src/SilverStripe/BehatExtension/Context/EmailContext.php
@@ -14,8 +14,7 @@ Behat\Gherkin\Node\TableNode;
 use Symfony\Component\DomCrawler\Crawler;
 
 // PHPUnit
-require_once 'PHPUnit/Autoload.php';
-require_once 'PHPUnit/Framework/Assert/Functions.php';
+require_once BASE_PATH . '/vendor/phpunit/phpunit/src/Framework/Assert/Functions.php';
 
 /**
  * Context used to define steps related to email sending.
diff --git a/src/SilverStripe/BehatExtension/Context/FixtureContext.php b/src/SilverStripe/BehatExtension/Context/FixtureContext.php
index e365e8b..9888be6 100644
--- a/src/SilverStripe/BehatExtension/Context/FixtureContext.php
+++ b/src/SilverStripe/BehatExtension/Context/FixtureContext.php
@@ -9,8 +9,7 @@ use Behat\Behat\Context\BehatContext,
 	SilverStripe\Filesystem\Storage\AssetStore;
 
 // PHPUnit
-require_once 'PHPUnit/Autoload.php';
-require_once 'PHPUnit/Framework/Assert/Functions.php';
+require_once BASE_PATH . '/vendor/phpunit/phpunit/src/Framework/Assert/Functions.php';
 
 /**
  * Context used to create fixtures in the SilverStripe ORM.
diff --git a/src/SilverStripe/BehatExtension/Context/LoginContext.php b/src/SilverStripe/BehatExtension/Context/LoginContext.php
index 81fb553..9a27d90 100644
--- a/src/SilverStripe/BehatExtension/Context/LoginContext.php
+++ b/src/SilverStripe/BehatExtension/Context/LoginContext.php
@@ -11,8 +11,7 @@ use Behat\Gherkin\Node\PyStringNode,
 Behat\Gherkin\Node\TableNode;
 
 // PHPUnit
-require_once 'PHPUnit/Autoload.php';
-require_once 'PHPUnit/Framework/Assert/Functions.php';
+require_once BASE_PATH . '/vendor/phpunit/phpunit/src/Framework/Assert/Functions.php';
 
 /**
  * LoginContext
diff --git a/src/SilverStripe/BehatExtension/Context/SilverStripeContext.php b/src/SilverStripe/BehatExtension/Context/SilverStripeContext.php
index 0e9aa94..9f18272 100644
--- a/src/SilverStripe/BehatExtension/Context/SilverStripeContext.php
+++ b/src/SilverStripe/BehatExtension/Context/SilverStripeContext.php
@@ -20,6 +20,8 @@ use Symfony\Component\Yaml\Yaml;
 // Mink etc.
 require_once 'vendor/autoload.php';
 
+require_once BASE_PATH . '/vendor/phpunit/phpunit/src/Framework/Assert/Functions.php';
+
 /**
  * SilverStripeContext
  *
-- 
2.3.5

```

**Comment by dhensby** [comment]
@chillu patch applied.

Why do we need to manually import these paths? We should be using the auto-loader as this is coupling our code to the file structure that could change and sets us up for more pain in the future...

**Comment by chillu** [comment]
> Why do we need to manually import these paths? We should be using the auto-loader as this is coupling our code to the file structure that could change and sets us up for more pain in the future...

Because there's no function-based autoloading - `Functions.php` doesn't contain any classes, only global functions. And we only really need to require this once in this behat extension, not in any custom feature context. Yes, I agree it's not ideal, but the lesser evil compared to the verbosity of `PHPUnit_Framework_Assert::assertSame()` in my opinion (and the upgrade pains for every project)

**Comment by dhensby** [comment]
Ok. Understood

**Comment by chillu** [comment]
Rebased, and pushed with the following commits:
https://github.com/silverstripe-labs/silverstripe-behat-extension/commit/4010d987f97889c8709585c2909e42fb1ac26dd6
https://github.com/silverstripe-labs/silverstripe-behat-extension/commit/350392148fc3ed9b764bf7a319f6d9b18e854701
https://github.com/silverstripe-labs/silverstripe-behat-extension/commit/899ed1c2260af4abff4bfcdbac508e3ff68c2b5e

**Pull request closed without merging**
